"""Styled .xlsx export (openpyxl)."""

from __future__ import annotations

from collections import defaultdict
from datetime import date
from io import BytesIO
from zoneinfo import ZoneInfo

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from timecalc import DayRow, split_hms

ORANGE = "F27329"
CHARCOAL = "3A3D40"
ICE = "F8FAFC"
STATUS_FILL = {
    "PRESENT": ("D1FAE5", "065F46"),
    "ABSENT": ("FEE2E2", "991B1B"),
    "PENDING": ("FEF3C7", "92400E"),
    "LEAVE": ("E0F2FE", "075985"),
    "HOLIDAY": ("EDE9FE", "5B21B6"),
    "WEEK_OFF": ("F1F5F9", "475569"),
}
STATUS_LABEL = {
    "PRESENT": "Present",
    "ABSENT": "Absent",
    "PENDING": "Pending review",
    "LEAVE": "On leave",
    "HOLIDAY": "Holiday",
    "WEEK_OFF": "Weekly off",
}
HEADERS = [
    "Employee ID",
    "Name",
    "Date",
    "Shift",
    "Clock-In",
    "Clock-Out",
    "Standard Duration",
    "Overtime Duration",
    "Total Duration (hh:mm:ss)",
    "Attendance Status",
]
WIDTHS = [14, 26, 13, 20, 19, 19, 18, 18, 24, 18]
DUR = "[h]:mm:ss"  # Excel duration format: stays correct past 24h and is summable
thin = Side(style="thin", color="E2E8F0")
BORDER = Border(top=thin, bottom=thin, left=thin, right=thin)


def _safe(value: str) -> str:
    """Neutralise spreadsheet formula injection from user-controlled text."""
    return "'" + value if value[:1] in ("=", "+", "-", "@", "\t", "\r") else value


def _local(dt, tz: str):
    return dt.astimezone(ZoneInfo(tz)).replace(tzinfo=None) if dt else None


def build_workbook(
    rows: list[DayRow], d_from: date, d_to: date, generated_by: str
) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Attendance"
    ws.sheet_view.showGridLines = False

    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(HEADERS))
    ws["A1"] = f"Attendance report  {d_from:%d %b %Y} to {d_to:%d %b %Y}"
    ws["A1"].font = Font(name="Inter", size=14, bold=True, color="FFFFFF")
    ws["A1"].fill = PatternFill("solid", fgColor=ORANGE)
    ws["A1"].alignment = Alignment(vertical="center", indent=1)
    ws.row_dimensions[1].height = 30
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(HEADERS))
    ws["A2"] = (
        f"Generated by {_safe(generated_by)}. Times are shown in each employee's office time zone."
    )
    ws["A2"].font = Font(name="Inter", size=9, italic=True, color="64748B")

    for c, (h, w) in enumerate(zip(HEADERS, WIDTHS), start=1):
        cell = ws.cell(row=4, column=c, value=h)
        cell.font = Font(name="Inter", bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=CHARCOAL)
        cell.alignment = Alignment(
            horizontal="center", vertical="center", wrap_text=True
        )
        cell.border = BORDER
        ws.column_dimensions[get_column_letter(c)].width = w
    ws.row_dimensions[4].height = 32

    r = 5
    for row in rows:
        vals = [
            _safe(row.emp_code),
            _safe(row.full_name),
            row.day,
            f"{_safe(row.shift_name)} ({row.shift_range})",
            _local(row.first_in, row.tz),
            _local(row.last_out, row.tz),
            row.standard / 86400,
            row.overtime / 86400,
            row.worked / 86400,
            STATUS_LABEL[row.status] + (" (on duty)" if row.is_open else ""),
        ]
        for c, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=c, value=v)
            cell.font = Font(name="Inter", size=10)
            cell.border = BORDER
            cell.alignment = Alignment(
                vertical="center", horizontal="left" if c <= 4 else "center"
            )
            if r % 2 == 0:
                cell.fill = PatternFill("solid", fgColor=ICE)
        ws.cell(row=r, column=3).number_format = "DD MMM YYYY"
        ws.cell(row=r, column=5).number_format = "DD MMM HH:mm:ss"
        ws.cell(row=r, column=6).number_format = (
            "DD MMM HH:mm:ss"  # shows the +1 day for night shifts
        )
        for c in (7, 8, 9):
            ws.cell(row=r, column=c).number_format = DUR
        bg, fg = STATUS_FILL[row.status]
        sc = ws.cell(row=r, column=10)
        sc.fill = PatternFill("solid", fgColor=bg)
        sc.font = Font(name="Inter", size=10, bold=True, color=fg)
        if row.overtime:
            ws.cell(row=r, column=8).font = Font(
                name="Inter", size=10, bold=True, color=ORANGE
            )
        r += 1

    last = r - 1
    if last >= 5:
        ws.auto_filter.ref = f"A4:{get_column_letter(len(HEADERS))}{last}"
    ws.freeze_panes = "C5"
    ws.page_setup.orientation = "landscape"
    ws.page_setup.fitToWidth = 1
    ws.sheet_properties.pageSetUpPr.fitToPage = True

    # ---- Summary sheet: exact totals per employee ----
    sm = wb.create_sheet("Summary")
    sm.sheet_view.showGridLines = False
    heads = [
        "Employee ID",
        "Name",
        "Present days",
        "Absent days",
        "Total hours",
        "Total minutes",
        "Total seconds",
        "Total (hh:mm:ss)",
        "Overtime (hh:mm:ss)",
    ]
    for c, h in enumerate(heads, start=1):
        cell = sm.cell(row=1, column=c, value=h)
        cell.font = Font(name="Inter", bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=CHARCOAL)
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
        sm.column_dimensions[get_column_letter(c)].width = (
            18 if c > 2 else 26 if c == 2 else 14
        )

    per: dict = defaultdict(lambda: {"present": 0, "absent": 0, "worked": 0, "ot": 0})
    meta: dict = {}
    for row in rows:
        k = row.employee_id
        meta[k] = (row.emp_code, row.full_name)
        per[k]["present"] += 1 if row.first_in else 0
        per[k]["absent"] += 1 if row.status == "ABSENT" else 0
        per[k]["worked"] += row.worked
        per[k]["ot"] += row.overtime
    for i, (k, agg) in enumerate(
        sorted(per.items(), key=lambda kv: meta[kv[0]][0]), start=2
    ):
        t = split_hms(agg["worked"])
        vals = [
            _safe(meta[k][0]),
            _safe(meta[k][1]),
            agg["present"],
            agg["absent"],
            t["hours"],
            t["minutes"],
            t["seconds"],
            agg["worked"] / 86400,
            agg["ot"] / 86400,
        ]
        for c, v in enumerate(vals, start=1):
            cell = sm.cell(row=i, column=c, value=v)
            cell.font = Font(name="Inter", size=10)
            cell.border = BORDER
            if c >= 3:
                cell.alignment = Alignment(horizontal="center")
        sm.cell(row=i, column=8).number_format = DUR
        sm.cell(row=i, column=9).number_format = DUR
    sm.freeze_panes = "C2"

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
